<?php
$url = $this->url(null, [], ['force_canonical' => true], true);
if($this->overwriteUrl != ''){
    $url = $this->overwriteUrl;
}

$parametersAdd = '';
foreach ($this->parameters as $name => $value) {
    $parametersAdd .= '&' . $name . '=' . $value;
}
?>

<?php foreach ($this->exportRenderers as $type => $name) : ?>
    <?php $urlExport = $url . '?' . $this->generalParameterNames['rendererType'] . '=' . $type . $parametersAdd; ?>
    <a class="btn btn-default btn-sm" href="<?= $urlExport ?>">
        <?= $name ?>
    </a>
<?php endforeach ?>
