<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_ZfcDataGrid
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @author Andrey Andreev <andrey.andreev1995@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>

<?php if ($navButtons): ?>
	<script>
        <?php $request = $this->current('request') ?>
        <?php if (!$request->hasHeader('X-Requested-With')) : ?>
        <?php $this->inlineScript()->captureStart(); ?>
        <?php endif; ?>

        <?php
        $grid = '#' . $gridId . '_grid';
        $pager = '#' . $gridId . '_pager';
        ?>
        $(document).ready(function () {

            <?php foreach ($navButtons as $button) : ?>

            <?php
            $opts = json_encode($button->getOptions());
            ?>

          // add first custom button
          $("<?php echo $grid ?>").jqGrid('navButtonAdd', "<?php echo $pager ?>", {
            caption: "<?php echo $button->getCaption() ?>",
            buttonicon: "<?php echo $button->getIcon() ?>",
            title: "<?php echo $button->getTitle() ?>",
            position: "<?php echo $button->getPosition() ?>",
            cursor: "<?php echo $button->getCursor() ?>",
            id: "<?php echo $button->getId() ?>",
            onClickButton:
              function () {
                $.fn.navButton.<?= $button->getName() ?>("<?php echo $gridId?>", <?php echo $opts?>);
              }
          });
            <?php endforeach; ?>
        });


        <?php if (!$request->hasHeader('X-Requested-With')) : ?>
        <?php $this->inlineScript()->captureEnd(); ?>
        <?php endif; ?>
	</script>
<?php endif; ?>